version: 2

project_name: MediaWarp

git:
  ignore_tags:
    - pre-release

snapshot:
  version_template: "PreRelease-v{{ incpatch .Version }}-{{ .ShortCommit }}"

release:
  name_template: "{{ .Tag }}"
  extra_files:
    - glob: ./LICENSE

before:
  hooks:
    - go mod download

builds:
  - skip: false
    env:
      - GOPROXY=https://goproxy.io,direct
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarm: 7
    binary: "{{ .ProjectName }}"
    ldflags:
      - -s -w
      - -X github.com/wenzhanquan/Wzq-MediaWarp/internal/config.appVersion={{ .Version }}
      - -X github.com/wenzhanquan/Wzq-MediaWarp/internal/config.commitHash={{ .FullCommit }}
      - -X github.com/wenzhanquan/Wzq-MediaWarp/internal/config.buildDate={{ .Date }}

dockers:
  # AMD64 镜像
  - image_templates:
      - "wenzhanquan/mediawarp:{{ .Version }}-amd64"
    dockerfile: docker/Dockerfile.goreleaser
    goos: linux
    goarch: amd64

  # ARM64 镜像
  - image_templates:
      - "wenzhanquan/mediawarp:{{ .Version }}-arm64"
    dockerfile: docker/Dockerfile.goreleaser
    goos: linux
    goarch: arm64

  # ARMv7 镜像
  - image_templates:
      - "wenzhanquan/mediawarp:{{ .Version }}-armv7"
    dockerfile: docker/Dockerfile.goreleaser
    goos: linux
    goarch: arm
    goarm: 7

docker_manifests:
  # 正式发布时，自动将上面三个架构的镜像合并为一个带版本号的 Tag
  - name_template: "wenzhanquan/mediawarp:{{ .Version }}"
    image_templates:
      - "wenzhanquan/mediawarp:{{ .Version }}-amd64"
      - "wenzhanquan/mediawarp:{{ .Version }}-arm64"
      - "wenzhanquan/mediawarp:{{ .Version }}-armv7"
  # 正式发布时，自动合并为 latest
  - name_template: "wenzhanquan/mediawarp:latest"
    image_templates:
      - "wenzhanquan/mediawarp:{{ .Version }}-amd64"
      - "wenzhanquan/mediawarp:{{ .Version }}-arm64"
      - "wenzhanquan/mediawarp:{{ .Version }}-armv7"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{ .Arch }}{{- if .Arm}}v{{ .Arm }}{{- end}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: LICENSE
      - src: README.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^ci:"
      - "^release:"
      - "^issue:"
      - "^MediaWarp"
