FROM alpine:latest

# 直接拷贝 GoReleaser 在各架构上下文根目录下准备好的二进制文件
COPY MediaWarp /MediaWarp

RUN chmod +x /MediaWarp

EXPOSE 9000
VOLUME ["/etc/localtime", "/etc/timezone", "/config", "/logs", "/custom"]
ENTRYPOINT ["/MediaWarp"]
