FROM alpine:latest

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/MediaWarp ./MediaWarp

RUN chmod +x ./MediaWarp

EXPOSE 9000
VOLUME ["/etc/localtime", "/etc/timezone", "/config", "/logs", "/custom"]
ENTRYPOINT ["/MediaWarp"]